#!/bin/bash

pushd $1

function start () {
    prevcolor=$2
    color=$2
    printf '#[fg=%s,bg=%s] ' $1 $2
}

function transition () {
    prevcolor=$color
    color=$1
    printf ' #[fg=%s,bg=%s]#[fg=%s] ' $prevcolor $color $2
}

start black blue
printf '#S'

transition yellow black
printf '%s' $(whoami)

transition magenta black
printf '#h'

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  transition brightyellow black
  printf ' %s' $(git branch | grep \* | cut -d ' ' -f2-)
fi

transition default default
