#!/bin/sh
opts="suspend\nlock\nlogout\nshutdown\nrestart"
case $(echo $opts | wofi --dmenu -p 'quit') in
    suspend)
        systemctl suspend
        ;;
    lock)
        ~/.config/sway/scripts/lock
        ;;
    logout)
        swaymsg exit
        ;;
    shutdown)
        shutdown now
        ;;
    restart)
        reboot
        ;;
esac
