#!/bin/bash

if check tv; then
    fzfcmd=tv
elif check sk; then
    fzfcmd=sk
elif check fzf; then
    fzfcmd=fzf
fi

if [ "$1" = '-' ]; then
    git checkout -
elif [ -z "$@" ]; then
    git branch | sed 's/^[* ]*//' | $fzfcmd | xargs git checkout
else
    git branch | sed 's/^[* ]*//' | $fzfcmd -1 -0 -q "$@" | xargs git checkout
fi
