#!/bin/bash

if check tv; then
    fzfcmd=tv
    fzfone="sk -1 -0 -q"
elif check sk; then
    fzfcmd=sk
    fzfone="sk -1 -0 -q"
elif check fzf; then
    fzfcmd=fzf
    fzfone="fzf -1 -0 -q"
fi

if [ "$1" = '-' ]; then
    git checkout -
elif [ -z "$@" ]; then
    git branch | sed 's/^[* ]*//' | $fzfcmd | xargs git checkout
else
    git branch | sed 's/^[* ]*//' | $fzfone "$@" | xargs git checkout
fi
