#!/bin/bash

cd $(dirname $0)

dot_config () {
    ln -sfh "$(pwd)/$1" "$HOME/.config/$1"
}

ln -sfh "$(pwd)/bin" "$HOME/.bin"
export PATH="$PATH:$HOME/.bin"
export SKIN=${SKIN:-onedark}

. "themes/$SKIN"
variables=$(cat "themes/$SKIN" | grep '^export' | sed 's/^export \([^=]*\).*/$\1/')
for file in $(find . -name '*.template' -type f); do
    cd "$(dirname "$file")"
    envsubst "$variables \$PWD" < "$(basename "$file")" > "$(basename "${file%.template}")"
    cd - >/dev/null
done

test -d "./syncat/style/$SKIN" && ln -sfh "./$SKIN" "./syncat/style/active"
check broot && dot_config broot
check fish && dot_config fish
check flashfocus && dot_config flashfocus
check hunter && dot_config hunter
check joshuto && dot_config joshuto
check kak && dot_config kak
check kitty && dot_config kitty
check mako && dot_config mako
check nvim && dot_config nvim
check ranger && dot_config ranger
check rofi && dot_config rofi
check sway && dot_config sway
check tig && dot_config tig
check topgrade && dot_config topgrade
check syncat && dot_config syncat
check waybar && dot_config waybar
ln -sf "$(pwd)/git/.gitconfig" "$HOME/.gitconfig"
ln -sf "$(pwd)/bash/.bashrc" "$HOME/.bashrc"
ln -sf "$(pwd)/tmux/.tmux.conf" "$HOME/.tmux.conf"
ln -sfh "$(pwd)/fonts" "$HOME/.fonts"

chmod +x ./tmux/scripts/tmux-status-left
