[[mgr.prepend_keymap]]
on = "d"
run = "noop"
[[mgr.prepend_keymap]]
on = "<C-->"
run = "noop"
[[mgr.prepend_keymap]]
on = "_"
run = "noop"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = "link --relative"

[[mgr.prepend_keymap]]
on = "s"
run = "search --via=rg"
[[mgr.prepend_keymap]]
on = "S"
run = "noop"
[[mgr.prepend_keymap]]
on = ["z", "h"]
run = "hidden --toggle"
[[mgr.prepend_keymap]]
on = "Z"
run = "noop"

[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"

[[mgr.prepend_keymap]]
on = ["m", "k"]
run = "shell --interactive --block 'mkdir -p '"

[[mgr.prepend_keymap]]
on = "-"
run = """
shell --block 'git reset "$1"'
"""

[[mgr.append_keymap]]
on = "+"
run = """
shell --block 'git add "$1"'
"""

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
