[[manager.prepend_keymap]]
on = "l"
run = [
    'shell -- [ -d "$1" ] && ya emit enter || true',
    'shell -- [ -f "$1" ] && ya emit open --hovered || true'
]

[[manager.prepend_keymap]]
on = ["z", "h"]
run = "hidden toggle"

[[manager.prepend_keymap]]
on = ["m", "k"]
run = "shell --interactive --block 'mkdir -p '"
