[flavor]
dark  = ""
light = ""

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { italic = true }

# Marker
marker_copied   = { fg = "lightgreen",  bg = "lightgreen" }
marker_cut      = { fg = "lightred",    bg = "lightred" }
marker_marked   = { fg = "lightcyan",   bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}

# Count
count_copied   = { fg = "white", bg = "green" }
count_cut      = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

# Highlighting
syntect_theme = ""

[mode]
normal_main = { bg = "magenta", fg = "black" }
normal_alt  = { bg = "blue", fg = "black" }

# Select mode
select_main = { bg = "red", bold = true }
select_alt  = { fg = "red", bg = "gray" }

# Unset mode
unset_main = { bg = "red", bold = true }
unset_alt  = { fg = "red", bg = "gray" }

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "darkgray" }
perm_type  = { fg = "green" }
perm_read  = { fg = "yellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "cyan" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error  = { fg = "red", bg = "black" }

[which]
cols            = 3
mask            = { bg = "black" }
cand            = { fg = "lightcyan" }
rest            = { fg = "darkgray" }
desc            = { fg = "lightmagenta" }
separator       = "  "
separator_style = { fg = "darkgray" }

[confirm]
border     = { fg = "blue" }
title      = { fg = "blue" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

[spot]
border = { fg = "blue" }
title  = { fg = "blue" }

# Table
tbl_col  = { fg = "blue" }
tbl_cell = { fg = "yellow", reversed = true }

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""

[pick]
border   = { fg = "blue" }
active   = { fg = "magenta", bold = true }
inactive = {}

[input]
border   = { fg = "blue" }
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border   = { fg = "blue" }
active   = { reversed = true }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

[tasks]
border  = { fg = "blue" }
title   = {}
hovered = { fg = "magenta", underline = true }

[help]
on      = { fg = "cyan" }
run     = { fg = "magenta" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "black", bg = "white" }

[filetype]
rules = [
    # Images
    { mime = "image/*", fg = "yellow" },

    # Media
    { mime = "{audio,video}/*", fg = "magenta" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "red" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "cyan" },

    # Empty files
    # { mime = "inode/empty", fg = "red" },

    # Special files
    { url = "*", is = "orphan", bg = "red" },
    { url = "*", is = "exec"  , fg = "green" },

    # Dummy files
    { url = "*", is = "dummy", bg = "red" },
    { url = "*/", is = "dummy", bg = "red" },

    # Fallback
    # { url = "*", fg = "white" },
    { url = "*/", fg = "blue" }
]

[icon]
prepend_globs = [
    { url = "**/test_*.py", text = "", fg = "#ffbc03" },
]
