[manager]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
sort_translit = true

show_hidden = false
show_symlink = true

[preview]
wrap = "no"
tab_size = 8

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
