[tools]
"cargo:cargo-binstall" = "latest"
"cargo:eza" = "latest"
"cargo:fd-find" = "latest"
"cargo:fend" = "latest"
"cargo:git-delta" = "latest"
"cargo:https://github.com/foxfriends/trilogy" = "branch:main"
"cargo:https://github.com/ms-jpq/sad" = "branch:senpai"
"cargo:paper-terminal" = "latest"
"cargo:pastel" = "latest"
"cargo:ripgrep" = "latest"
"cargo:syncat" = "latest"
"cargo:tealdeer" = "latest"
"cargo:zoxide" = "latest"
"go:github.com/pdfrg/must/cmd/must" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
go = "latest"
node = "latest"
opentofu = "latest"
python = "latest"
rust = "latest"
television = "latest"
typst = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "yarn", "python", "pnpm", "npm"]
