###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
#
# https://dystroy.org/broot/skins
[skin]
default = "color(15) none / color(15) none"
tree = "grey none / grey none"
file = "ansi(0) none / ansi(0) none"
directory = "darkblue none bold / darkblue none bold"
exe = "green none"
link = "cyan none"
pruning = "gray(16) none italic"
perm__ = "ansi(0) none bold"
perm_r = "yellow none bold"
perm_w = "darkred none bold"
perm_x = "darkgreen none bold"
owner = "darkyellow none bold"
group = "darkyellow none bold"
count = "yellow none"
dates = "darkcyan none"
sparse = "ansi(214) none"
content_extract = "ansi(29) none"
content_match = "ansi(34) none"
git_branch = "yellow none"
git_insertions = "green none"
git_deletions = "darkred none"
git_status_current = "ansi(0) none"
git_status_modified = "yellow none"
git_status_new = "green none bold"
git_status_ignored = "ansi(0) none"
git_status_conflicted = "red none"
git_status_other = "ansi(0) none"
selected_line = "none gray(22)"
char_match = "magenta none"
file_error = "red none"
flag_label = "ansi(0) none"
flag_value = "darkblue none"
input = "grey none"
status_error = "ansi(0) darkred"
status_job = "ansi(220) gray(20)"
status_normal = "ansi(0) gray(20)"
status_italic = "ansi(0) gray(20) italic"
status_bold = "ansi(0) gray(20) bold"
status_code = "ansi(0) gray(20)"
status_ellipsis = "grey grey(20)"
purpose_normal = "ansi(0) gray(20)"
purpose_italic = "ansi(0) gray(20) italic"
purpose_bold = "ansi(0) gray(20) bold"
purpose_ellipsis = "ansi(0) gray(20)"
scrollbar_track = "grey none"
scrollbar_thumb = "ansi(0) none"
help_paragraph = "grey none"
help_bold = "grey none bold"
help_italic = "grey none italic"
help_code = "grey gray(20)"
help_headers = "darkmagenta none"
help_table_border = "ansi(0) none"
preview = "ansi(0) gray(22)"
preview_line_number = "ansi(0) gray(20)"
preview_match = "magenta none"
hex_null = "ansi(0) none"
hex_ascii_graphic = "grey none"
hex_ascii_whitespace = "ansi(0) none"
hex_ascii_other = "grey none"
hex_non_ascii = "ansi(0) none"
