###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
#
# https://dystroy.org/broot/skins
[skin]
default = "ansi(0) none / ansi(0) none"
tree = "ansi(15) none / ansi(15) none"
file = "grey none / ansi(15) none"
directory = "darkblue none bold / darkblue none bold"
exe = "green none"
link = "cyan none"
pruning = "gray(12) none italic"
perm__ = "ansi(15) none bold"
perm_r = "yellow none bold"
perm_w = "darkred none bold"
perm_x = "darkgreen none bold"
owner = "darkyellow none bold"
group = "darkyellow none bold"
count = "yellow none"
dates = "darkcyan none"
sparse = "ansi(214) none"
content_extract = "ansi(29) none"
content_match = "ansi(34) none"
git_branch = "yellow none"
git_insertions = "green none"
git_deletions = "darkred none"
git_status_current = "ansi(15) none"
git_status_modified = "yellow none"
git_status_new = "green none bold"
git_status_ignored = "ansi(15) none"
git_status_conflicted = "red none"
git_status_other = "ansi(15) none"
selected_line = "none gray(5) / none gray(4)"
char_match = "magenta none"
file_error = "red none"
flag_label = "ansi(15) none"
flag_value = "grey none"
input = "ansi(15) none / gray(15) gray(2)"
status_error = "ansi(0) darkred"
status_job = "ansi(220) gray(5)"
status_normal = "grey gray(3)"
status_italic = "grey gray(3) italic"
status_bold = "grey gray(3) bold"
status_code = "ansi(15) gray(3)"
status_ellipsis = "grey grey(3)"
purpose_normal = "ansi(15) gray(2)"
purpose_italic = "ansi(15) gray(2) italic"
purpose_bold = "ansi(15) gray(2) bold"
purpose_ellipsis = "ansi(15) gray(2)"
scrollbar_track = "grey none / gray(4) none"
scrollbar_thumb = "ansi(15) none / gray(14) none"
help_paragraph = "grey none"
help_bold = "grey none bold"
help_italic = "grey none italic"
help_code = "grey gray(3)"
help_headers = "darkmagenta none"
help_table_border = "ansi(15) none"
preview = "ansi(15) gray(2)"
preview_line_number = "ansi(15) gray(2)"
preview_match = "magenta none"
hex_null = "ansi(15) none"
hex_ascii_graphic = "grey none"
hex_ascii_whitespace = "ansi(15) none"
hex_ascii_other = "grey none"
hex_non_ascii = "ansi(15) none"
