#!/usr/bin/env bash

while :
do
    swaymsg -t get_workspaces -r | jq 'map(select(.focused == true)) | { text: .[0].representation }' -c
    swaymsg -t subscribe '["window", "binding"]' > /dev/null 2>&1
done
