# plugins
source "%val{config}/plugins.kak"

set global ui_options ncurses_set_title=false

# visuals
colorscheme syntax

declare-option -hidden bool lines_relative false
add-highlighter global/lines number-lines -separator ' │ ' -hlcursor
hook global -group lines GlobalSetOption lines_relative=true %{
    add-highlighter -override global/lines number-lines -separator ' │ ' -hlcursor -relative
}
hook global -group lines GlobalSetOption lines_relative=false %{
    add-highlighter -override global/lines number-lines -separator ' │ ' -hlcursor
}

add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -lf '¬' -spc '·' -nbsp '␣' -tab '⇥'

# tabulation
set global tabstop 4
set global indentwidth 4
map global insert <s-tab> '<esc><i'

# swap leader to <space>
map global normal , <space>
map global normal <space> ,
map global insert <c-space> '<esc>,'

# get hover info
map global insert <c-a> '<a-;>: lsp-hover<ret>'
map global normal <c-a> ': lsp-hover<ret>'

# insert mode word delete
map global insert <a-backspace> '<esc>b<a-d>i'
map global insert <a-del> '<esc>w<a-d>i'

map global normal v ':enter-user-mode modes<ret>'

# word movement with arrow keys in insert mode
map global normal <a-right> 'w'
map global normal <a-left> 'b'
map global insert <a-right> '<a-;>w'
map global insert <a-left> '<a-;>b'

# alias for old habits
alias global wqa write-all-quit
alias global W write
alias global Wq write-quit
alias global WQ write-quit
alias global Wqa write-all-quit
alias global WQa write-all-quit
alias global WQA write-all-quit

define-command -docstring 'set buffer filetype <type>' -params 1 sf %{
    set buffer filetype %arg{1}
}

hook -group kks global KakBegin .* %{
    require-module detection
    check-cmd kks
    eval %sh{ kks init }
}

hook -group pastel global KakBegin .* %{
    require-module pastel
    map global user c ': enter-user-mode pastel<ret>' -docstring 'pastel'
}
