# plugins
source "%val{config}/plugins.kak"

# visuals
colorscheme %sh{echo ${skin:-"onedark"}}
add-highlighter global/ number-lines -separator ' │ ' -hlcursor
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -lf '¬' -spc '·' -nbsp '␣' -tab '⇥'

# tabulation
set global tabstop 4
set global indentwidth 4
map global insert <s-tab> '<esc><i'

# swap leader to <space>
map global normal , <space>
map global normal <space> ,

# get hover info
map global insert <c-a> '<a-;>: lsp-hover<ret>'
map global normal <c-a> ': lsp-hover<ret>'

# insert mode word delete
map global insert <a-backspace> '<esc>b<a-d>i'
map global insert <a-del> '<esc>w<a-d>i'

# word movement with arrow keys in insert mode
map global normal <a-right> 'w'
map global normal <a-left> 'b'
map global insert <a-right> '<a-;>w'
map global insert <a-left> '<a-;>b'

# user mode commands
map global user z ': w<ret>' -docstring 'save'
map global user w ': trim-eol<ret>' -docstring 'trim-eol'
map global user l ': enter-user-mode lsp<ret>' -docstring 'lsp'
map global user k ': enter-user-mode windowing<ret>' -docstring 'windowing'
map global user f ': format<ret>' -docstring 'format'
map global user g ': enter-user-mode git<ret>' -docstring 'git'
map global user p ': fuzzyfind<ret>' -docstring 'fuzzy find'
map global user '\' ': browse<ret>' -docstring 'browse files'
map global user / ': comment-line<ret>'

# alias for old habits
alias global wqa write-all-quit
alias global W write
alias global Wq write-quit
alias global WQ write-quit
alias global Wqa write-all-quit
alias global WQa write-all-quit
alias global WQA write-all-quit

map global goto s '<esc>: open-related<ret>' -docstring 'cycle related files (existing)'
map global goto S '<esc>: open-related-new<ret>' -docstring 'cycle related files (create)'
map global goto L l -docstring 'l'
map global goto H h -docstring 'h'
map global goto J j -docstring 'j'
map global goto K k -docstring 'k'

declare-user-mode git
map global git a ': git add<ret>' -docstring 'add current file'
map global git A ': git add --all<ret>' -docstring 'add all files'
map global git c ': git commit<ret>' -docstring 'commit'
map global git s ': git status<ret>' -docstring 'status'
map global git j ': git next-hunk<ret>' -docstring 'goto next hunk'
map global git k ': git prev-hunk<ret>' -docstring 'goto previous hunk'
map global git h ': merge-take-ours<ret>' -docstring 'take first merge conflict option'
map global git l ': merge-take-theirs<ret>' -docstring 'take second merge conflict option'
map global git m ': merge-next-conflict<ret>' -docstring 'next merge conflict'
map global git i ': gh issue list -a foxfriends<ret>' -docstring 'list issues'

hook global BufWritePost .* "git show-diff"
hook global BufCreate .* "git show-diff"
set global ui_options ncurses_set_title=false

hook -group kks global KakBegin .* %{
    require-module detection
    check-cmd kks
    eval %sh{ kks init }
}

hook -group pastel global KakBegin .* %{
    require-module pastel
    map global user c ': enter-user-mode pastel<ret>' -docstring 'pastel'
}
