# plugins
source "%val{config}/plugins.kak"

set-option global ui_options ncurses_set_title=false

# visuals
colorscheme syntax

declare-option -hidden bool lines_relative false
add-highlighter global/lines number-lines -separator ' │ ' -hlcursor
hook global -group lines GlobalSetOption lines_relative=true %{
    add-highlighter -override global/lines number-lines -separator ' │ ' -hlcursor -relative
}
hook global -group lines GlobalSetOption lines_relative=false %{
    add-highlighter -override global/lines number-lines -separator ' │ ' -hlcursor
}

add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -lf '¬' -spc '·' -nbsp '␣' -tab '⇥'

# tabulation
set-option global tabstop 4
set-option global indentwidth 4

map global insert <s-tab> '<esc><i'
map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

# get hover info
map global insert <c-a> '<a-;>: lsp-hover<ret>'
map global normal <c-a> ': lsp-hover<ret>'

# insert mode word delete
map global insert <a-backspace> '<esc>b<a-d>i'
map global insert <a-del> '<esc>w<a-d>i'
# terminal line navigation
map global insert <c-w> '<esc>b<a-d>i'
map global insert <c-e> '<esc>gla'
map global insert <c-a> '<esc>ghi'

map global normal v ':enter-user-mode modes<ret>'

map global normal z ':w<ret>'
map global normal Z ':w<ret>'

# map global normal <ret> ':enter-user-mode user<ret>'

# word movement with arrow keys in insert mode
map global normal <a-right> 'w'
map global normal <a-left> 'b'
map global normal '#' ': run<ret>'
map global normal = '|fend "${kak_selection}" | tr -d "\n"<ret>' -docstring 'calculate'
map global insert <a-right> '<a-;>w'
map global insert <a-left> '<a-;>b'

# alias for old habits
alias global wqa write-all-quit
alias global W write
alias global Wq write-quit
alias global WQ write-quit
alias global Wqa write-all-quit
alias global WQa write-all-quit
alias global WQA write-all-quit

set-option global modelinefmt "%opt{lsp_modeline} %opt{modelinefmt}"

define-command -docstring 'set-option buffer filetype <type>' -params 1 sf %{
    set-option buffer filetype %arg{1}
}

hook -group kks global KakBegin .* %{
    require-module detection
    check-cmd kks
    eval %sh{ kks init }
}

hook -group env global KakBegin .* %{
    require-module detection
    require-module dotenv
    check-file .env
    dotenv-load
}

hook global BufSetOption filetype=gleam %{
    set-option buffer lsp_servers %{
        [gleam]
        root_globs = ["gleam.toml"]
        args = ["lsp"]
    }
}
