[default_view]

[[default_view.keymap]]
command = "escape"
keys = [ "escape" ]
[[default_view.keymap]]
command = "toggle_visual"
keys = [ "V" ]
[[default_view.keymap]]
command = "new_tab"
keys = [ "T" ]
[[default_view.keymap]]
command = "new_tab"
keys = [ "ctrl+t" ]
[[default_view.keymap]]
command = "close_tab"
keys = [ "W" ]
[[default_view.keymap]]
command = "close_tab"
keys = [ "ctrl+w" ]
[[default_view.keymap]]
command = "close_tab"
keys = [ "q" ]
[[default_view.keymap]]
command = "quit --output-current-directory"
keys = [ "Q" ]
[[default_view.keymap]]
command = "reload_dirlist"
keys = [ "R" ]
[[default_view.keymap]]
command = "toggle_hidden"
keys = [ "z", "h" ]

[[default_view.keymap]]
command = "tab_switch 1"
keys = [ "\t" ]
[[default_view.keymap]]
command = "tab_switch -1"
keys = [ "backtab" ]

[[default_view.keymap]]
command = "cursor_move_up"
keys = [ "arrow_up" ]
[[default_view.keymap]]
command = "cursor_move_up"
keys = [ "k" ]
[[default_view.keymap]]
command = "cursor_move_down"
keys = [ "arrow_down" ]
[[default_view.keymap]]
command = "cursor_move_down"
keys = [ "j" ]
[[default_view.keymap]]
command = "cursor_move_end"
keys = [ "end" ]
[[default_view.keymap]]
command = "cursor_move_end"
keys = [ "G" ]
[[default_view.keymap]]
command = "cursor_move_home"
keys = [ "home" ]
[[default_view.keymap]]
command = "cursor_move_home"
keys = [ "g", "g" ]
[[default_view.keymap]]
command = "cursor_move_page_up"
keys = [ "page_up" ]
[[default_view.keymap]]
command = "cursor_move_page_down"
keys = [ "page_down" ]

[[default_view.keymap]]
command = "open"
keys = [ "arrow_right" ]
filetype = "directory"
[[default_view.keymap]]
command = "open"
keys = [ "l" ]
filetype = "directory"
[[default_view.keymap]]
command = "quit --output-selected-files"
keys = [ "arrow_right" ]
filetype = "file"
[[default_view.keymap]]
command = "quit --output-selected-files"
keys = [ "l" ]
filetype = "file"

[[default_view.keymap]]
command = "open"
keys = [ "\n" ]
filetype = "directory"
[[default_view.keymap]]
command = "quit --output-selected-files"
keys = [ "\n" ]
filetype = "file"

[[default_view.keymap]]
command = "open_with"
keys = [ "r" ]

[[default_view.keymap]]
command = ":cd"
keys = [ "c", "d" ]
[[default_view.keymap]]
command = "cd .."
keys = [ "arrow_left" ]
[[default_view.keymap]]
command = "cd .."
keys = [ "h" ]

[[default_view.keymap]]
command = "cut_files"
keys = [ "d", "d" ]
[[default_view.keymap]]
command = "copy_files"
keys = [ "y", "y" ]
[[default_view.keymap]]
command = "paste_files"
keys = [ "p", "p" ]
[[default_view.keymap]]
command = "paste_files --overwrite=true"
keys = [ "p", "o" ]
[[default_view.keymap]]
command = "delete_files"
keys = [ "d", "D" ]
[[default_view.keymap]]
command = "delete_files"
keys = [ "delete" ]

[[default_view.keymap]]
command = ":touch "
keys = [ "insert" ]

[[default_view.keymap]]
command = ":touch "
keys = [ "f", "t" ]

[[default_view.keymap]]
command = "rename_append"
keys = [ "a" ]
[[default_view.keymap]]
command = "rename_prepend"
keys = [ "A" ]

[[default_view.keymap]]
command = "select --toggle=true"
keys = [ " " ]
[[default_view.keymap]]
command = "select --toggle=true --all=true"
keys = [ "t" ]

[[default_view.keymap]]
command = ":search "
keys = [ "/" ]
[[default_view.keymap]]
command = "search_next"
keys = [ "n" ]
[[default_view.keymap]]
command = "search_prev"
keys = [ "N" ]

[[default_view.keymap]]
command = "bulk_rename"
keys = [ "b", "b" ]
[[default_view.keymap]]
command = "set_mode"
keys = [ "=" ]

[[default_view.keymap]]
command = ":"
keys = [ ";" ]
[[default_view.keymap]]
command = ":"
keys = [ ":" ]
[[default_view.keymap]]
command = ":mkdir "
keys = [ "m", "k" ]
[[default_view.keymap]]
command = ":rename "
keys = [ "c", "w" ]

[[default_view.keymap]]
command = "sort lexical"
keys = [ "s", "l" ]
[[default_view.keymap]]
command = "sort mtime"
keys = [ "s", "m" ]
[[default_view.keymap]]
command = "sort natural"
keys = [ "s", "n" ]
[[default_view.keymap]]
command = "sort reverse"
keys = [ "s", "r" ]

[[default_view.keymap]]
command = "cd /"
keys = [ "g", "/" ]
[[default_view.keymap]]
command = "cd /etc"
keys = [ "g", "e" ]

[task_view]
keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]

[help_view]
keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]
