[extension]

## text formats
build = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
c = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
cmake = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
conf = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
cpp = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
css = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
eex = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
ex = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
exs = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
go = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
h = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
hpp = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
hs = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
html = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
ini = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
java = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
js = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
kt = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
log = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
md = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
ninja = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
py = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
rs = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
sh = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
toml = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
txt = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
xml = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]

# archive formats
bz2 = [
    { command = "tar", args = [ "-xvjf" ], confirm_exit = true }, 
    { command = "file-roller", fork = true, silent = true },
    { command = "less", confirm_exit = true } ]
gz = [
    { command = "tar", args = [ "-xvzf" ], confirm_exit = true },
    { command = "file-roller", fork = true, silent = true },
    { command = "less", confirm_exit = true } ]
rar = [
    { command = "unrar", args = [ "e" ], confirm_exit = true },
    { command = "file-roller", fork = true, silent = true },
    { command = "less", confirm_exit = true } ]
xz = [
    { command = "tar", args = [ "-xvJf" ], confirm_exit = true },
    { command = "file-roller", fork = true, silent = true },
    { command = "less", confirm_exit = true } ]
zip = [
    { command = "unzip", confirm_exit = true },
    { command = "file-roller", fork = true, silent = true },
    { command = "less", confirm_exit = true } ]

# misc formats
odt = [
    { command = "libreoffice", fork = true, silent = true } ]
odf = [
    { command = "libreoffice", fork = true, silent = true } ]
pdf = [
    { command = "open", fork = true, silent = true } ]

tex = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "pdflatex" },
    { command = "syncat -gffen", confirm_exit = true } ]

[mimetype]
text = [
    { command = "kak" },
    { command = "nvim" },
    { command = "nano" },
    { command = "atom", fork = true, silent = true },
    { command = "syncat -gffen", confirm_exit = true } ]
