#!/bin/bash

# base 16
export theme_black=383a42
export theme_light_black=a0a1a7
export theme_red=e45649
export theme_light_red=b33022
export theme_green=50a14f
export theme_light_green=50a14f
export theme_yellow=c18401
export theme_light_yellow=e08026
export theme_blue=248be0
export theme_light_blue=375670
export theme_magenta=c678dd
export theme_light_magenta=a626a4
export theme_cyan=0997b4
export theme_light_cyan=0997b4
export theme_white=d4d4d4
export theme_light_white=fafafa

# ANSI codes
export theme_ansi_bg=37
export theme_ansi_fg=40

# UI
export theme_color_default=$theme_black
export theme_color_bgdefault=$theme_light_white
export theme_color_divider=$theme_white
export theme_color_highlight=$theme_blue
export theme_color_bghighlight=$theme_light_white
export theme_color_error=$theme_light_red
export theme_color_status=$theme_color_default
export theme_color_bgstatus=$theme_color_bghighlight
export theme_color_date=$theme_cyan
export theme_color_cursor=$theme_color_default
export theme_color_bgcursor=$theme_color_bgdefault
export theme_color_bghighlight2=e5e5e5
export theme_color_placeholder=$theme_light_black

# code
export theme_color_keyword=$theme_magenta
export theme_color_operator=$theme_magenta
export theme_color_function=$theme_blue
export theme_color_builtin=$theme_cyan
export theme_color_string=$theme_green
export theme_color_path=$theme_green
export theme_color_constant=$theme_light_yellow
export theme_color_value=$theme_light_yellow
export theme_color_type=$theme_yellow
export theme_color_comment=$theme_light_black
export theme_color_escape=$theme_cyan
export theme_color_variable=$theme_red
export theme_color_name=$theme_red
export theme_color_meta=$theme_cyan
export theme_color_invisible=$theme_color_bghighlight

# markup
export theme_color_title=$theme_red
export theme_color_emphasis=$theme_yellow
export theme_color_strong=$theme_magenta
export theme_color_link=$theme_cyan

# shell
export theme_file_directory=$theme_blue
export theme_file_executable=$theme_green
export theme_file_link=$theme_cyan
export theme_file_socket=$theme_magenta
export theme_file_image=$theme_yellow
export theme_file_media=$theme_magenta
export theme_file_archive=$theme_red
export theme_file_perm_r=$theme_yellow
export theme_file_perm_w=$theme_red
export theme_file_perm_x=$theme_green

# prompt
export theme_color_host=$theme_magenta
export theme_color_user=$theme_yellow
export theme_color_vcs=$theme_light_yellow
export theme_color_tab=$theme_cyan

# tmux
export theme_tmux_session=$theme_white
export theme_tmux_bgsession=$theme_blue
export theme_tmux_user=$theme_white
export theme_tmux_bguser=$theme_color_user
export theme_tmux_host=$theme_white
export theme_tmux_bghost=$theme_color_host
export theme_tmux_vcs=$theme_white
export theme_tmux_bgvcs=$theme_color_vcs

# git
export theme_addition_background=e8f0e6
export theme_addition_foreground=c3ddbf
export theme_addition=$theme_green
export theme_deletion_background=f7e4e0
export theme_deletion_foreground=ecb8ac
export theme_deletion=$theme_red
export theme_git_modification=$theme_yellow
export theme_git_syntax_theme=OneHalfLight

eval $(env | grep '^theme' | sed 's/\([a-fA-F0-9]\{6\}\)$/"$(pastel format rgb \1)"/ ; s/theme_/export theme_rgb_/')
