#!/bin/bash
set -e
curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
PATH="$PATH:$HOME/.pyenv/bin"
latest=$(pyenv install --list | grep '^ *[0-9.]*$' | tail -n 1 | sed 's/ *//')
pyenv install "$latest"
pyenv global "$latest"
