#!/bin/bash
set -e
cd $(dirname $0)
if [ $(uname) == 'Darwin' ]; then
    check brew || ./brew
    brew install tmux
else
    test -d "$HOME/.local/libevent" || ./libevent
    cd "$HOME/.local"
    git clone git@github.com:tmux/tmux
    cd tmux
    sh autogen.sh
    ./configure && make
    sudo make install
fi
