#!/bin/bash
set -e
cd $(dirname $0)
if [ $(uname) == 'Darwin' ]; then
    check brew || ./brew
    brew install tmux
else
    ./libevent
    cd "$HOME/.local"
    test -d "tmux" || git clone git@github.com:tmux/tmux
    cd tmux
    git pull
    sh autogen.sh
    ./configure && make
    sudo make install
fi
