#!/bin/bash
config=""
here=$PWD
while [ "$here" != '.' -a "$here" != '/' ]; do
    if [ -f "$here/deno.json" ]; then
        config="--config $here/deno.json"
        break
    elif [ -f "$here/deno.jsonc" ]; then
        config="--config $here/deno.jsonc"
        break
    fi
    here=$(dirname "$here")
done

deno fmt $config -
