#!/usr/bin/env bash
set +e
f="$1"
shift
g=$(mktemp)

yazi --chooser-file "$g" "$@"
file=$(< "$g")

if [ -n "$file" ]; then
    printf "edit! -existing '%s'\n" "$file" > "$f" &
else
    printf 'echo "No file selected"\n' > "$f" &
fi

rm "$g"
