map global goto s '<esc>: open-related<ret>' -docstring 'cycle related files (existing)'
map global goto S '<esc>: open-related-new<ret>' -docstring 'cycle related files (create)'
map global goto L l -docstring 'l'
map global goto H h -docstring 'h'
map global goto J j -docstring 'j'
map global goto K k -docstring 'k'
